### ISSUE TITLE
element IDs contain information

### ISSUE THREAD

**Issue by jiskattema** [cltl/NAF-4-Development#3]
The NAF document requires identifiers to use a prefix depending on the type of element: 'w' for words, 't' for terms, etc.. Additionally, some of the Newsreader pipeline tools expect the rest of the id to be a number.

This is contrary to the 'NAF should be simple' design of NAF.

**Comment by sarnoult** [comment]
You are entirely right. The id prefixes are only conventional and the requirement to follow this convention is limited to the Newsreader project. They have nothing to do with the NAF format itself, so you are free to use any ids you like, or almost:
the only requirement from the NAF specification is that the _ids for a number of elements, including word forms and terms, should be unique in a document_. This is because higher-level annotations are anchored to spans of word forms or terms. This means for instance that you cannot give ids like "1", "2", etc. to both the text and terms layer.
